// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ReFont",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ReFont",
            targets: ["AppModule"],
            bundleIdentifier: "com.heejin.ReFont",
            teamIdentifier: "Q8UK3SWSPM",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .tv),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "PicSweep requires access to a photo library."),
                .camera(purposeString: "PicSweep requires access to a camera."),
                .photoLibraryAdd(purposeString: "PicSweep requires access to a photo library.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)